### ISSUE TITLE
Network error when load external CSS

### ISSUE THREAD

**Issue by brandonhilkert** [fphilipe/premailer-rails#105]
I have `action_mailer.asset_host` set. and include this in the layout:

`<%= stylesheet_link_tag "mailer", media: "all" %>`

Should I be doing something different?

```
irb(main):001:0> UserMailer.signup(User.find(1)).deliver
  Rendered user_mailer/signup.html.erb within layouts/mailer (1.1ms)
  Rendered user_mailer/signup.html.erb within layouts/mailer (1.1ms)
NoMethodError: undefined method `request_uri' for #<URI::Generic:0x007f1aa0deba18>
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http/generic_request.rb:19:in `initialize'
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http/request.rb:14:in `initialize'
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1280:in `new'
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1280:in `request_get'
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:480:in `block in get_response'
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:583:in `start'
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:478:in `get_response'
    from /app/vendor/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:455:in `get'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/css_loaders/network_loader.rb:9:in `load'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/css_helper.rb:33:in `block in load_css'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/css_helper.rb:32:in `each'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/css_helper.rb:32:in `load_css'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/css_helper.rb:19:in `block in css_for_doc'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/css_helper.rb:19:in `map'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/css_helper.rb:19:in `css_for_doc'
... 3 levels...
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/hook.rb:81:in `generate_text_part'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/hook.rb:62:in `generate_alternative_part'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/hook.rb:50:in `generate_html_part_replacement'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/hook.rb:24:in `perform'
    from /app/vendor/bundle/ruby/2.1.0/gems/premailer-rails-1.7.0/lib/premailer/rails/hook.rb:8:in `perform'
    from /app/vendor/bundle/ruby/2.1.0/gems/mail-2.5.4/lib/mail/mail.rb:230:in `block in inform_interceptors'
```

**Comment by shopjoy** [comment]
Thanks @brandonhilkert for sharing your insight. I also forgot the same thing.

**Comment by scottrobertson** [comment]
I am getting this, even though the file is in the assets list :S
