### ISSUE TITLE
undefined method `force_encoding' when using rails preview

### ISSUE THREAD

**Issue by DannyBen** [fphilipe/premailer-rails#147]
Hi,

My rails mailer preview used to work fine and show HTML when I used a different inline css plugin.
Now, the preview gives me the above error.

My mailer layout has this line to bring in the CSS:
```html
<link rel="stylesheet" href="/assets/mailer.css">
```

And the CSS file is in `public/assets/mailer.css`

Sending works fine (although I got the same error at first when I did not have the leading slash in the stylesheet reference) but preview gives the error.

**Comment by fphilipe** [comment]
Please provide the full error message, which ruby version you're using and the gem version.

**Comment by DannyBen** [comment]
Sure.

#### Error log when requesting a preview:
```
Started GET "/rails/mailers/mailer/enbrel" for 10.0.2.2 at 2015-12-30 13:10:11 +0000

<...truncated...>

Completed 500 Internal Server Error in 228ms (ActiveRecord: 0.6ms)

NoMethodError - undefined method `force_encoding' for #<Array:0x0000000507f440>:
  premailer-rails (1.8.2) lib/premailer/rails/css_helper.rb:19:in `block in css_for_doc'
  premailer-rails (1.8.2) lib/premailer/rails/css_helper.rb:19:in `css_for_doc'
  premailer-rails (1.8.2) lib/premailer/rails/customized_premailer.rb:15:in `initialize'
  premailer-rails (1.8.2) lib/premailer/rails/hook.rb:85:in `premailer'
  premailer-rails (1.8.2) lib/premailer/rails/hook.rb:75:in `generate_html_part'
  premailer-rails (1.8.2) lib/premailer/rails/hook.rb:52:in `generate_html_part_replacement'
  premailer-rails (1.8.2) lib/premailer/rails/hook.rb:24:in `perform'
  premailer-rails (1.8.2) lib/premailer/rails/hook.rb:8:in `perform'
  actionmailer (4.2.5) lib/action_mailer/preview.rb:113:in `block in inform_preview_interceptors'
  actionmailer (4.2.5) lib/action_mailer/preview.rb:112:in `inform_preview_interceptors'
  actionmailer (4.2.5) lib/action_mailer/preview.rb:67:in `call'
  railties (4.2.5) lib/rails/mailers_controller.rb:22:in `preview'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  <...truncated new relic, rack, puma...>

```

#### Ruby Version
```
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

#### Rails Version: 4.2.5

#### Premailer version (installed it today, so recent I supposed)
This is the snippet from Gemfile.lock
```
    premailer (1.8.6)
      css_parser (>= 1.3.6)
      htmlentities (>= 4.0.0)
    premailer-rails (1.8.2)
      actionmailer (>= 3, < 5)
      premailer (~> 1.7, >= 1.7.9)

```

**Comment by fphilipe** [comment]
Found the problem. This happens when all loading strategies fail. I'm fixing this, but this means that you have another problem :wink:

**Comment by DannyBen** [comment]
Hmm.... how come the sender works and the preview does not?

I am not doing anything special to my knowledge... is there a better way to include CSS than what I did? I actually didnt like the fact that its in the public folder. Was trying to make it work from the app/assets/stylesheets folder without success. 

Also tried setting css through the premailer config, didnt seem to find the correct "combination"...

Any tip as to what is wrong and/or what is the best (read: easiest and cleanest to read) way to load that CSS would be great.

**Comment by fphilipe** [comment]
Take a look at the example application in this repo. Maybe that helps. Try using the asset pipeline like in the example. Have a look at how the email view specifies the asset.

**Comment by DannyBen** [comment]
Aha! Thanks, missed that examples folder.
