### ISSUE TITLE
Can't run premailer on separate queue server

### ISSUE THREAD

**Issue by seanhandley** [fphilipe/premailer-rails#182]
I've split my Rails production server into two: a background server that runs redis/sidekiq and a frontend server running unicorn/rails.

If I schedule an email delivery using the `Mailer.action(args).deliver_later` then it fails with `Failed to open TCP connection to :80` (i.e. it's setting the host to be the empty string).

See below for a manually triggered example in the rails console on the queue server. The queue server has the same code as the web server but there's no unicorn/nginx web service running on 80/443.

```
irb(main):001:0> Mailer.activation_reminder('sean.handley@gmail.com').deliver_now
  Rendering mailer/activation_reminder.html.erb
  Rendered mailer/_header.html.erb (0.7ms)
  Rendered mailer/_footer.html.erb (0.5ms)
  Rendered mailer/activation_reminder.html.erb (9.5ms)
Mailer#activation_reminder: processed outbound mail in 603.9ms
Errno::ECONNREFUSED: Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:479:in `get_response'
	from /home/rails/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http.rb:456:in `get'
	from /home/rails/stronghold/vendor/bundle/ruby/2.3.0/gems/premailer-rails-1.9.3/lib/premailer/rails/css_loaders/network_loader.rb:9:in `load'
	from /home/rails/stronghold/vendor/bundle/ruby/2.3.0/gems/premailer-rails-1.9.3/lib/premailer/rails/css_helper.rb:41:in `block in load_css'
	from /home/rails/stronghold/vendor/bundle/ruby/2.3.0/gems/premailer-rails-1.9.3/lib/premailer/rails/css_helper.rb:40:in `each'
	from /home/rails/stronghold/vendor/bundle/ruby/2.3.0/gems/premailer-rails-1.9.3/lib/premailer/rails/css_helper.rb:40:in `load_css'
	from /home/rails/stronghold/vendor/bundle/ruby/2.3.0/gems/premailer-rails-1.9.3/lib/premailer/rails/css_helper.rb:21:in `css_for_url'
	from /home/rails/stronghold/vendor/bundle/ruby/2.3.0/gems/premailer-rails-1.9.3/lib/premailer/rails/css_helper.rb:17:in `block in css_for_doc'
```

I've tried setting the `base_url` for premailer via the docs recommendation but it makes no difference.

Any ideas how to further debug and fix would be great!

**Comment by seanhandley** [comment]
I see reference to asset_host in the code. If it's relevant, my config uses this as the assets host:

```ruby
  config.action_controller.asset_host = "//assets-cdn.datacentred.io"
  config.action_mailer.asset_host = config.action_controller.asset_host
```

**Comment by fphilipe** [comment]
I think it could be due to the protocol relative asset host, which makes little sense for emails. AFAIK, you can simply specify the domain, i.e. drop the `//` and it will still be protocol relative (Rails will construct the URL in views with the current protocol) and things will work in your emails.

**Comment by seanhandley** [comment]
Thanks @fphilipe - I'll try it and see.

**Comment by fphilipe** [comment]
Feel free to reopen if not successful.

**Comment by seanhandley** [comment]
Still not working I'm afraid. Same issue.

**Comment by seanhandley** [comment]
(I can't see an option to reopen)

**Comment by fphilipe** [comment]
@seanhandley Reopened. Sorry, won't be able to help you right now as I'm going away for two weeks 🤔

**Comment by seanhandley** [comment]
Thanks @fphilipe - speak more when you're back. For now I've fallen back to using some custom code via premailer itself but I'd like a less obtrusive solution.

**Comment by fphilipe** [comment]
So when setting

```ruby
config.action_controller.asset_host = "assets-cdn.datacentred.io"
config.action_mailer.asset_host = config.action_controller.asset_host
```

it still doesn't work?

**Comment by seanhandley** [comment]
I'm afraid not @fphilipe. I've tried everything I can think of.

I'm confused why it's trying to connect to port 80 in the first place?

**Comment by fphilipe** [comment]
Can you share the HTML of your email with premailer disabled? I'd like to see what `<link/>` tag is being output. premailer-rails reads out those tags and loads the URL by applying these changes:

- If the URL is merely a path, it'll use the asset host to construct a URL. If the asset host is merely a domain without a schema, it'll use `http`.
- If the URL is a protocol relative URL (e.g. `//host.com/foo.css`), it'll prefix `http` to it.
- If the URL is a complete URL, it'll just use that.

So port 80 is used whenever the schema is resolved to `http` as that, as you're probably well aware of, is the default port for that schema.

**Comment by seanhandley** [comment]
```
Date: Wed, 08 Mar 2017 10:38:13 +0000
From: DataCentred <noreply@datacentred.io>
To: foo@bar.com
Message-ID: <58bfdf156f67b_aec3fb58ecff124519ca@my.datacentred.io.mail>
Subject: Activate your DataCented account
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
skip-premailer: true

<link rel="stylesheet" media="screen" href="//assets-cdn.datacentred.io/assets/email-1757dd8219a77de19ab9a4f07882d67e25515543b6daaa910a377831259ee6e3.css" />

<div class="container" id="email">
  <div class="pull-right"><img class="logo_email" alt="" src="https://assets-cdn.datacentred.io/assets/DC_Mono_B-903aac5ca4f5c6887193d880dbd1196deb8a978027eef5cb32de78b66d085935.png" /></div>
<div class="push"></div>

  <h1>Please activate your account</h1>

  <p>Once you're activated, you will only be charged for the resources you use.</p>
  
  <div style: "padding: 30px">
    <a class="confirm" target='_blank' href="https://my.datacentred.io/activate">Activate Account</a>
  </div>

  <h2>Can I activate over the phone?</h2>
  <p>Yes! Call <a href="tel:+44 161 870 3981">+44 161 870 3981</a> between 9am and 5pm GMT and we'll activate your account for you.</p>

  <h2>Why do I need to activate?</h2>

  <p>We need to verify your identity to activate your account, even if you have a discount code that provides a free trial. This is purely to prevent fraudulent use of our cloud services.</p>

  <ul><li>You will only get charged for the resources you use. If you don't use anything, you will not be charged and you're free to cancel your account at any time.</li></ul>

  <p>Kind regards,<br/>
  The DataCentred Team</p>
</div>
<div class='footer' id="email">
  <div class="pull-right">
    <p><a href="http://www.datacentred.co.uk" target="_blank">datacentred.co.uk</a></p>
  </div>
  <p>&copy; DataCentred Ltd 2017</p>
</div>
<div class="push"></div>
```

**Comment by seanhandley** [comment]
I think I'm onto the fix. It needs "https://assets-cdn.datacentred.io"

**Comment by seanhandley** [comment]
Ok, strange. I can get the emails delivered if I use the `https://` prefixed assets host but premailer doesn't seem to be picking up and inlining the styles. Here's the email it's sending:

```
<link rel="stylesheet" media="screen" href="https://assets-cdn.datacentred.io/email.css" />

<div class="container" id="email">
  <div class="pull-right"><img class="logo_email" alt="" src="https://assets-cdn.datacentred.io/DC_Mono_B.png" /></div>
<div class="push"></div>

  <h1>Please activate your account</h1>

  <p>Once you're activated, you will only be charged for the resources you use.</p>
  
  <div style: "padding: 30px">
    <a class="confirm" target='_blank' href="https://my.datacentred.io/activate">Activate Account</a>
  </div>

  <h2>Can I activate over the phone?</h2>
  <p>Yes! Call <a href="tel:+44 161 870 3981">+44 161 870 3981</a> between 9am and 5pm GMT and we'll activate your account for you.</p>

  <h2>Why do I need to activate?</h2>

  <p>We need to verify your identity to activate your account, even if you have a discount code that provides a free trial. This is purely to prevent fraudulent use of our cloud services.</p>

  <ul><li>You will only get charged for the resources you use. If you don't use anything, you will not be charged and you're free to cancel your account at any time.</li></ul>

  <p>Kind regards,<br/>
  The DataCentred Team</p>
</div>
<div class='footer' id="email">
  <div class="pull-right">
    <p><a href="http://www.datacentred.co.uk" target="_blank">datacentred.co.uk</a></p>
  </div>
  <p>&copy; DataCentred Ltd 2017</p>
</div>
<div class="push"></div>
```

**Comment by seanhandley** [comment]
Got it - the stylesheet URL was wrong. All seems to be working fine now. Thanks for the help!
