### ISSUE TITLE
TypeError (no implicit conversion of nil into String)

### ISSUE THREAD

**Issue by te-chris** [fphilipe/premailer-rails#220]
I'm still getting this error from #207 , however I've updated to the latest version of premailer-rails.

Please see the below stacktrace:

```
[ActiveJob] [ActionMailer::DeliveryJob] [06e5eba9-5a98-492e-97d8-ac9f829fc16f] Error performing ActionMailer::DeliveryJob (Job ID: 06e5eba9-5a98-492e-97d8-ac9f829fc16f) from Async(mailers) in 12.27ms: TypeError (no implicit conversion of nil into String):
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_loaders/file_system_loader.rb:22:in `join'
/.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_loaders/file_system_loader.rb:22:in `asset_filename'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_loaders/file_system_loader.rb:17:in `file_name'
/.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_loaders/file_system_loader.rb:8:in `load'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_helper.rb:47:in `block in load_css'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_helper.rb:46:in `each'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_helper.rb:46:in `load_css'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_helper.rb:20:in `css_for_url'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_helper.rb:13:in `block in css_for_doc'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_helper.rb:13:in `map'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/css_helper.rb:13:in `css_for_doc'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/customized_premailer.rb:14:in `initialize'
/.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/hook.rb:97:in `new'
rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/hook.rb:97:in `premailer'
.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/hook.rb:86:in `generate_text_part'
/.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/hook.rb:62:in `generate_alternative_part'
/.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/hook.rb:50:in `generate_html_part_replacement'
/.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/hook.rb:24:in `perform'
/.rvm/gems/ruby-2.4.1/gems/premailer-rails-1.10.2/lib/premailer/rails/hook.rb:8:in `perform'
/.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/mail.rb:235:in `block in inform_interceptors'
.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/mail.rb:234:in `each'
.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/mail.rb:234:in `inform_interceptors'
.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:248:in `inform_interceptors'
.rvm/gems/ruby-2.4.1/gems/mail-2.7.0/lib/mail/message.rb:258:in `deliver

```

**Comment by te-chris** [comment]
Ok, so I've been digging into this a bit and have 99% found the cause:

We do something a bit weird here with our emails in our Admin: In order for our ops team to be able to edit and personalise certain emails, we render them as HTML into an `<iframe>` in a form in our admin interface. The email body is set to `contenteditable` then, when they're done, we just send the html straight out.

This is where the bug comes in.

I use the chrome extension shutup to remove comments from the web - highly recommend it.... This works by adding a `<link>` tag:
```<link id="shut-up-css" rel="stylesheet" href="data:text/css;base64,LyogCiAqIHNodXR1cC5jc3MKICogd2ViIC0gcGVhbnV0IGdhbGxlcnkgPSBibGlzcwogKgogKiBieSBTdGV2ZW4gRnJhbmsgPHN0ZXZlbmZAcGFuaWMuY29tPiBhbmQgY29udHJpYnV0b3JzCiAqIDxodHRwczovL3N0ZXZlbmYuY29tL3NodXR1cGNzcy8+CiAqCiAqIFBsZWFzZSBkbyBub3QgdXNlIHNodXR1cC5jc3MgaW4gZGVyaXZhdGl2ZSB3b3JrcyAoc3VjaCBhcyBpT1MgCiAqIENvbnRlbnQgQmxvY2tlcnMgb3IgYnJvd3NlciBleHRlbnNpb25zKSB3aXRob3V0IHBlcm1pc3Npb24uCiAqIAogKiBOb3RlczoKICoKICogMS4gSWYgeW91IHdhbnQgdG8gUkUtRU5BQkxFIGNvbW1lbnRzIGZvciBhIHNwZWNpZmljIHNpdGUsIGFkZCBhbgogKiBvdmVycmlkZSBhZnRlciBpbXBvcnRpbmcgdGhpcyBmaWxlLiAgRm9yIGV4YW1wbGUsIHRvIHJlLWVuYWJsZQogKiBqdXN0IFNsYXNoZG90IGNvbW1lbnRzOgogKiAgCiAqIEBpbXBvcnQgdXJsKCJodHRwczovL3N0ZXZlbmYuY29tL3NodXR1cC9zaHV0dXAtbGF0ZXN0LmNzcyIpOwogKiAKICogI2NvbW1lbnRsaXN0aW5nIHsKICogICAgIGRpc3BsYXk6IGluaGVyaXQgIWltcG9ydGFudDsKICogfQogKgogKiBCZSBhd2FyZSB0aGF0IHNvbWUgc2l0ZXMgbWF5IGJlIGFmZmVjdGVkIGJ5IG1vcmUgdGhhbiBvbmUgcnVsZS4KICoKICogMi4gSWYgeW91J2QgbGlrZSB0byBqdXN0IGZhZGUgY29tbWVudHMgb3V0IHJhdGhlciB0aGFuIGNvbXBsZXRlbHkgCiAqIHJlbW92ZSB0aGVtIGZyb20gdGhlIHBhZ2U6CiAqIAogKiBSZXBsYWNlOgogKiAgICAgZGlzcGxheTogbm9uZSAhaW1wb3J0YW50OwogKgogKiBXaXRoIHNvbWV0aGluZyBsaWtlOgogKiAgICAgb3BhY2l0eTogMC4xOwogKgogKi8KCi8qIFlvdVR1YmUgKHN0YW5kYXJkIGFuZCBGZWF0aGVyIGludGVyZmFjZXMpICovCgojd2F0Y2gtY29tbWVudC1wYW5lbCwKI2NtLAojd2F0Y2gtY29tbWVudHMtY29yZSwKI3dhdGNoLWRpc2N1c3Npb24sCgovKiBZb3VUdWJlIChsYXRlIDIwMTMsIEcrIGludGVncmF0aW9uKSAqLwoKI2NvbW1lbnRzLXRlc3QtaWZyYW1lLAoKLyogCiAqIERpZ2cgYW5kIG90aGVyIHNpdGVzIHRoYXQgdXNlICJjb21tZW50cyIgZGl2cwogKiAoTWFrZSBhbiBleGNlcHRpb24gZm9yIDxjb2RlPiBlbGVtZW50cywgd2hvc2UgImNvbW1lbnRzIiBhcmUKICogYSBkaWZmZXJlbnQgYW5pbWFsKSAKKi8KCi5jb21tZW50czpub3QoY29kZSksCi5Db21tZW50czpub3QoY29kZSksCiNjb21tZW50czpub3QoY29kZSksCiNDb21tZW50czpub3QoY29kZSksCiNjb21tZW50c19jb250YWluZXIsCgovKiBDTk4gYW5kIG90aGVyIHNpdGVzIHRoYXQgdXNlIERpc3F1cyAqLwoKI2Rpc3F1c190aHJlYWQsCiNkc3EtY29udGVudCwKCi8qIEFpbid0IEl0IENvb2wgTmV3cyAqLwoKLmJsb2NrLXRhbGtiYWNrX3N0b3J5LAoKLyogVmVyc2lvblRyYWNrZXIgKi8KCiNwcm9kUmV2aWV3cywKCi8qIE1hY1VwZGF0ZSAqLwoKLnJldmNvbnRlbnQsCgovKiBXb3JkUHJlc3MgZGVmYXVsdCBLdWJyaWNrIHRoZW1lIGFuZCBkZXNjZW5kZW50cyAqLwoKLmNvbW1lbnRsaXN0LAoKLyogU2xhc2hkb3QgKi8KCiNjb21tZW50bGlzdGluZywKCi8qIENCQyBOZXdzICovCgojc29jaWFsY29tbWVudHMsCiNjb21tZW50d3JhcHBlciwKCi8qIEN8TmV0IE5ld3MuY29tICovCgouY29tbWVudHdyYXBwZXIsCgovKiBSZWRkaXQgKi8KCi5jb21tZW50YXJlYSwKCi8qIERlc2lnbmVyIE5ld3MgKi8KCiNzdG9yeS1jb21tZW50cywKCi8qIE9yZWdvbkxpdmUgYW5kIGdlbmVyaWMgImNvbW1lbnQiIGNsYXNzICovCgouY29tbWVudCwKCi8qIEtBVFUgKi8KCiNjb21tZW50Zm9ybSwKCi8qIFdhc2hpbmd0b24gUG9zdCBhbmQgb3RoZXIgc2l0ZXMgdGhhdCB1c2UgImNvbW1lbnRUZXh0IiBkaXZzICovCgouY29tbWVudFRleHQsCgovKiBHYW5uZXR0IG5ld3NwYXBlcnMgYW5kIG90aGVyIHNpdGVzIHRoYXQgdXNlIFBsdWNrICovCgpkaXYjcGx1Y2tjb21tZW50cywKCi8qIExhc3QuZm0gc2hvdXRib3ggKi8KCmRpdiNwYWdlIGRpdiNjb250ZW50IGgyI3Nob3V0Ym94LCBkaXYjcGFnZSBkaXYjY29udGVudCBkaXYjc2hvdXRib3hDb250YWluZXIsCgovKiBUaGUgR2xvYmUgYW5kIE1haWwgKi8KCiNsYXRlc3QtY29tbWVudHMsCgovKiBFVyAqLwoKLmNvbW1lbnRIb2xkZXIsCgovKiBVbmtub3duICovCgouY29tbWVudHMtbGlzdCwKI2Jsb2dDb21tZW50cywKI2NvbW1lbnRzX3BhbmUsCiNjb21tZW50Y29udGFpbmVyLAojY29tbWVudHNEaXYsCgovKiBCb3hlZSAqLwoKLmNvbW1lbnQtY29udGFpbmVyLCAKI2NvbW1lbnQtY29udGFpbmVyLAoKLyogTUxCICovCgojY29tbWVudF9jb250YWluZXIsCgovKiBDTk4gKi8KCiNjb21tZW50YmxvYiwKI2NubkNvbW1lbnRzLAoKLyogVGhlIFN0cmFuZ2VyICovCgojQnJvd3NlQ29tbWVudHMsCgovKiBZYWhvbyBOZXdzICovCgoubXdwcGh1LWNvbW1lbnRzLAoudWdjY210LWNvbW1lbnRzLAoKLyogQ29kaW5nIEhvcnJvciAqLwoKLmNvbW1lbnRzLWJvZHksCgovKiBzZWVuIG9uIFJldXRlcnMgKi8KCi5hcnRpY2xlQ29tbWVudHMsCgovKiBuYXRpb25hbHBvc3QuY29tIChQbHVjaykgKi8KCi5wbHVjay1jb21tLAoKLyogS0FUVSAqLwoKLnBhZ2UtY29tbWVudHMsCgovKiBEZXZpYW50QXJ0ICovCgojZ21pLUNDb21tZW50TWFzdGVyLAoKLyogU29tZSBibG9ncyAqLwoKLmNvbW1lbnRzLWNvbnRhaW5lciwKCi8qIE9wcmFoICovCgojbWVkaWFfY29tbWVudHMsCgovKiA5dG81bWFjICovCgojaWRjLWNvbnRhaW5lci1wYXJlbnQsCgovKiBMaXZlZnlyZSAqLwoKI2xpdmVmeXJlX2NvbW1lbnRfc3RyZWFtLAojbGl2ZWZ5cmUtYm9keSwKI2xpdmVmeXJlLAouZnlyZSwKCi8qIFBDIFdvcmxkICovCgojYXJ0aWNsZUNvbW1lbnRzLAoKLyogU2xhdGUgKi8KCi5qcy1Db21tZW50c0FyZWEsCgovKiBOWVRpbWVzIEJsb2dzICovCgojcmVhZGVyQ29tbWVudHMsCi5yZWFkZXJDb21tZW50cywKI2NvbW1lbnRzQ29udGFpbmVyLAouY29tbWVudHNDb250YWluZXIsCi5jb21tZW50c01vZHVsZSwKCi8qIG55dGltZXMuY29tICovCgpzcGFuLnBvc3RNZXRhSGVhZGVyQ29tbWVudENvdW50LmNvbW1lbnRDb3VudCwKYnV0dG9uLmNvbW1lbnRzLWJ1dHRvbiwKYS5jb21tZW50Q291bnRMaW5rLApwLnRoZW1lLWNvbW1lbnRzLAoKLyogQkJDIE5ld3MgKi8KCi5kbmEtY29tbWVudCwKCi8qIFpETmV0ICovCgoudmlldy02LCAKLnNwYWNlLV81LAoKLyogR2FtYXN1dHJhICovCgouYWxsX2NvbW1lbnRzLAoKLyogZHZpY2UuY29tICovCgojZGlzcGxheV9jb21tZW50cywKCi8qIGhwLmNvbSAqLwoKLmFydGljbGUtY29tbWVudHMsCgovKiB1bmlvbmxlYWRlci5jb20gKi8KCiNjb21tZW50c2NvbnRhaW5lciwKCi8qIGlmYy5jb20gKi8KCi5lY2hvLXN0cmVhbS1jb250YWluZXIsCgovKiBjcmVhdGl2ZXJldmlldy5jby51ayAqLwoKI2ZlZWRiYWNrLAoKLyogdGhlbmV4dHdlYi5jb20gKi8KCiNsZl9jb21tZW50cywKI2xmX3R3aXR0ZXJfY29tbWVudHMsCiNsZl9mYWNlYm9va19jb21tZW50cywKI2xmX2NvbW1lbnRfc3RyZWFtLAoKLyogTWFjV29ybGQgKi8KCiNjb21tZW50TGlzdCwKCi8qIGZ0LmNvbSAqLwoKI2luZmVybm8tY29tbWVudHMsCgovKiB0aWRiaXRzLmNvbSAqLwoKLmNiX2Jsb2NrLAoKLyogZGlsYmVydC5jb20gKi8KCi5DTVRfQ29tbWVudExpc3QsCgovKiBDcmFja2VkICovCiAKI2NvbW1lbnRzX3NlY3Rpb24sCgovKiBGYWNlYm9vayBmZWVkYmFjayAqLwoKLmZiLWNvbW1lbnRzLAouVUZJQ29tbWVudCwKZmJcOmNvbW1lbnRzLAoKLyogYnV6emZlZWQgKi8KCiNyZXNwb25zZXMsCiNmYWNlYm9va19yZXNwb25zZXMsCiNmYWNlYm9va19jb252ZXJzYXRpb25zLAojZmJfY29tbWVudHNfd3JhcHBlciwKI2ZiX2NvbW1lbnRzX2NvbnRyb2wsCi5mYi1jb21tZW50cy1hcmVhLAojcmVzcG9uZCwKI2JhZGdlX3ZvdGluZywKCi8qIHNwaWVnZWwuZGUgKi8KCi5zcENvbW1lbnRzQm94Qm9keSwKCi8qIGF1dG8tbW90b3ItdW5kLXNwb3J0LmRlICovCgoua29tbWVudGFyZV91ZWJlcnNpY2h0LAoKLyogY29ycmllcmUuaXQgKi8KCiNib2R5X2RsdCwKI2NvbW1lbnRfYm94X2FydGljbGUsCgovKiByZXB1YmJsaWNhLml0ICovCgojdWdjLWNvbnRhaW5lciwKI2dzLXNvY2lhbC1jb21tZW50cywKLmdpZy1jb21tZW50cy1jb250YWluZXIsCgovKiBmYXoubmV0ICovCgouQXJ0aWtlbEtvbW1lbnRpZXJlbiwKCi8qIEdpYW50IEJvbWIgYXZhdGFycyAqLwoKLmNvbW1lbnQtYXZhdGFyLXdyYXAsCgovKiBobG50di5jb20gKi8KCi5mYkZlZWRiYWNrQ29udGVudCwKCi8qIG1pcnJvci5jby51ayAqLwoKLnBsdWNrLXdyYXAsCgovKiBUd2l0UGljICovCgojbWVkaWEtY29tbWVudHMsCgovKiBHdWFyZGlhbiAqLwoKI2QyLXJvb3QsCgovKiBFISBPbmxpbmUgKi8KCi50aHltZS1jb21tZW50LWxpc3QsCgovKiBTb3VuZENsb3VkICovCgouY29tbWVudHNMaXN0X19pdGVtIC5jb21tZW50SXRlbSwKLmNvbW1lbnRQb3BvdmVyLAoKLyogUGVubnkgQXJjYWRlIHJlcG9ydCAqLwoKI3ZhbmlsbGEtY29tbWVudHMsCgovKiBNb3RoZXIgTmF0dXJlIE5ldHdvcmsgKi8KCi5yZXBsaWVzLXdyYXBwZXIgPiAucmVwbGllcywKLnZpZXctY29tbWVudC1saXN0LAoKLyogTmV3IEphbG9wbmlrIChhbmQgR2F3a2VyPykgKi8KCi5qc19yZXBsaWVzLAoKLyogVFNOLmNhICovCgojdHNuWW91ckNhbGxTdG9yeSwKCi8qIEhTLmZpICovCgoja29tbWVudGl0LAoKLyogTmV3c0JsdXIgKi8KCi5OQi1mZWVkLXN0b3J5LWNvbW1lbnRzLAoKLyogUnVzc2lhIFRvZGF5ICovCi5iLWNvbW1lbnRzX3BhZ2UsCgovKiBIZWFyc3Qgc2l0ZXMgKi8KLmhkbi1jb21tZW50cywKCi8qIENveCBNZWRpYSBzaXRlcyAqLwojY21Db21tZW50cywKCi8qIGNsZXZlbGFuZC5jb20gKi8KLnJ0Yi1hcHBzLWNvbW1lbnRzLWNvbnRhaW5lciwKCi8qIGRlcnN0YW5kYXJkLmF0ICovCi5jb21tdW5pdHlDYW52YXMsCgovKiBwcmVzc2UuYXQgKi8KI2NvbW1lbnRib3gsCiNuZXdjb21tZW50Zm9ybSwKCi8qIGthLW5ld3MuZGUgKi8KI1F1aWNrUmVnQ29uLAoKLyogdGFnZXNzY2hhdS5kZSAqLwoubW9kQ29uLm1vZENvbkNvbW1lbnRzLAoKLyogdGF6LmRlICovCi5mdWxsLmNvbW11bml0eS5wYWdlLmxhc3QuZXZlbiwKCi8qIHNwaWVnZWwuZGUgKi8KLmNsZWFyZml4LmFydGljbGUtY29tbWVudHMtYm94Lm1vZHVsZS1ib3gsCgovKiBoYW5kZWxzYmxhdHQuY29tICovCi5oY2YtYXJ0aWNsZS5oY2YtY29udGVudC5oY2YtYXJ0aWNsZS10eXBlMiwKCi8qIGZyLW9ubGluZS5kZSAqLwojY29tbWVudHNSb290LAouQ29tbWVudCwKCi8qIGh1ZmZpbmd0b25wb3N0LmRlICovCiNjb252ZXJzYXRpb25zLWh1ZmZwb3N0LXdlYi1tYWluLAoKLyogdGFnZXNzcGllZ2VsLmRlKi8KI2hjZi1jb21tZW50LXdyYXBwZXIuaGNmLWNvbW1lbnRzLAojY29tbWVudElucHV0LmhjZi1jb21tZW50cy1pbnB1dCwKLmhjZi1jb21tZW50cywKCi8qIHdpd28uZGUgKi8KLmhjZi1kZXRhaWwuaGNmLWNvbW1lbnRzLWNvbnRhaW5lciwKCi8qIGFyc3RlY2huaWNhLmNvbSAqLwoKYXNpZGUuY29tbWVudHMtaG90bmVzcywKYS5jb21tZW50LWNvdW50LApkaXYuY29tbWVudHMtYmFyLAoKLyogdHJha3QudHYgKi8KCi5zdW1tYXJ5LWNvbW1lbnRzLAoKLyogS290YWt1ICovCi5wb3N0LWNvbnRlbnQgLmFubm90YXRpb24tZm9vdG5vdGUtd3JhcHBlciwKLnBvc3QtY29udGVudCAuYW5ub3RhdGVCdXR0b24sCgovKiBpbWd1ciAqLwojY29tbWVudHMtY29udGFpbmVyLAoKLyogQ3VyYmVkICovCi5wb3N0LWNvbW1lbnRzLW1vZHVsZSwKI2NvbW1lbnRzLWNvdW50LAouY29tbWVudHMtYm9keS1jb250YWluZXIsCgovKiBQb2x5Z29uICovCi5tLWhlcm9fX2NvbW1lbnQtY291bnQsCi5jb21tZW50X2NvdW50LAoKLyogU0IgTmF0aW9uICovCi5tLWNvbW1lbnQtY291bnRfX2J1YmJsZSwKLm0tc3RyZWFtX19ub2RlLWxpc3RfX2NvbW1lbnRzLAoKLyogVGhlIFZlcmdlICovCltkYXRhLXVpPWNvbW1lbnRdLAoKLyogbGVtb25kZS5mciAqLwoubGlzdGVfcmVhY3Rpb25zLAoKLyogbGVmaWdhcm8uZnIgKi8KI3JlYWdpciwKCi8qIHJ1ZTg5Lm5vdXZlbG9icy5jb20gKi8KI2NvbW1lbnRhaXJlcywKCi8qIG51bWVyYW1hLmNvbSAqLwouY29tbWVudGFpcmVzLAoKLyogaHVmZmluZ3RvbnBvc3QuZnIgKi8KI2NvbnZlcnNhdGlvbnMtaHVmZnBvc3Qtd2ViLAoKLyogQ2l2aWwgQ29tbWVudHMgKi8KI2NpdmlsLWNvbW1lbnRzLAoKLyogOWdhZyAqLwoucG9zdC1jb21tZW50LAoKLyogRW5nYWRnZXQgKENvbmZhYikgKi8KLmNvbmZhYiwKCi8qIEdhbWFzdXRyYSAqLwojZHluYW1pY2NvbW1lbnRzLAoKLyogR2FtZVNwb3QgKi8KLmNvbW1lbnRzLWJsb2NrLAoKLyogTElORSBXZWJ0b29uICovCi5jb21tZW50X2FyZWEsCgovKiBOQVZFUiBOZXdzICovCiNjYm94X21vZHVsZSwKCi8qIERBVU0gTmV3cyAqLwouY210X25ld3MsCgovKiBSYWRpby1DYW5hZGEgKi8KLnZpYWZvdXJhLAoKLyogTWVkaXVtICovCi5yZXNwb25zZXNXcmFwcGVyLAoucmVzcG9uc2VzU3RyZWFtV3JhcHBlciwKCi8qIEcxIGFuZCBHbG9ibyAqLwojYm94Q29tZW50YXJpb3MsCgovKiBVT0wgKi8KI2NvbWVudGFyaW9zLAoKLyogRm9saGEgKi8KI2FydGljbGUtY29tbWVudHMsCgovKiBWZWphICovCi5hYnJpbC1jb21lbnRhcmlvcy13aWRnZXQsCgovKiBWSyAqLwoucmVwbGllc193cmFwID4gZGl2OmZpcnN0LWNoaWxkLAojcHZfY29tbWVudHMud2FsbF9tb2R1bGUsCiNtdl9jb21tZW50cy53YWxsX21vZHVsZSwKCi8qIERhaWx5bW90aW9uICovCi5wbF92aWRlb19jb21tZW50X3Bvc3RfYW5kX2NvbW1lbnRzLAoKLyogRHV0Y2ggbGFuZ3VhZ2Ugd2Vic2l0ZXMsIGluY2x1ZGluZyBudS5ubCBhbmQgdHdlYWtlcnMubmV0ICovCi5yZWFjdGllcywKI3JlYWN0aWVzLAoKLyogaW52ZXN0b3IuYmcgYW5kIHBvc3NpYmx5IG90aGVycyAqLwoKLmNvbW1lbnRzX2FydGljbGUsCiNjb21tZW50cy1mcmFtZSwKCi8qIGhzLmZpICovCiNjb21tZW50aW5nLAoKLyogaWx0YXNhbm9tYXQuZmkgKi8KLmlzLWNvbW1lbnRzLXdpZGdldCwKCi8qIHRhbG91c3Nhbm9tYXQuZmkgKi8KLnhjQ29udGFpbmVyLAoKLyogTWFjUnVtb3JzIG1vYmlsZSBzaXRlIGNvbW1lbnRzIGxpbmsgKi8KLnRlYXNlciAudGVhc2VyX2Zvb3RlciA+IGEsCgovKiBVU2dhbWVyIHBhcmFncmFwaCBjb21tZW50IGJ1dHRvbnMgKi8KYS5idXR0b24uYW5ub3RhdGlvbi1jb3VudCwKCi8qIFR3aXRjaCBDaGF0ICovCiNyaWdodC1jb2x1bW4gLmNoYXQtcm9vbSwKLnJpZ2h0LWNvbHVtbiAuY2hhdC1yb29tX19jb250YWluZXIsCi5jaGFubmVsLXBhZ2VfX3JpZ2h0LWNvbHVtbiAuY2hhdF9fY29udGFpbmVyLAouY2hhdC1wYW5lIC5jaGF0LXBhbmVfX2NoYXQtbGlzdCwKCi8qIFlvdVR1YmUgTGl2ZSBDaGF0ICovCiN3YXRjaC1zaWRlYmFyLWxpdmUtY2hhdCwKeXRkLWxpdmUtY2hhdC1mcmFtZSwKCi8qIEdvQ29taWNzICovCi5qcy1jb21tZW50cy10aHJlYWQtY29udGFpbmVyLAoKLyogUGF0cmVvbiAqLwpbZGF0YS10ZXN0LXRhZz0iY29tbWVudC1yb3ciXSwKCi8qCiAqIEluc3RhZ3JhbS4KICogUHJvZmVzc2lvbmFsIGRyaXZlciwgY2xvc2VkIGNvdXJzZS4gRG8gbm90IGF0dGVtcHQuCiAqLwpzcGFuI3JlYWN0LXJvb3QgYXJ0aWNsZSBzZWN0aW9uICsgZGl2ID4gdWwgPiBsaSA+IGEubm90cmFuc2xhdGUsCnNwYW4jcmVhY3Qtcm9vdCBhcnRpY2xlIHNlY3Rpb24gKyBkaXYgPiB1bCA+IGxpID4gYS5ub3RyYW5zbGF0ZSArIHNwYW4sCgovKiBQaXhpdiAqLwojanMtbW91bnQtcG9pbnQtY29tbWVudC1tb2R1bGUsCi5jb21tZW50LWxpc3QsCgovKiBZYWhvbyEgTmV3cyBmbG9hdGluZyBjb21tZW50IGRpbmd1cyAqLwojWURDLU1haW5DYW52YXMgLmNhbnZhcy1zaGFyZS1idXR0b25zID4gZGl2Omxhc3QtY2hpbGQsCgovKiBSZWZpbmVyeTI5ICovCi5zcHByZV9jb252ZXJzYXRpb24tdmlldywKCi8qIFN0ZWFtIENvbW11bml0eSAqLwouY29tbWVudHRocmVhZF9hcmVhLAoKLyogLi4ubWlzYy4uLiAqLwoKI2NvbW1lbnRsaXN0LAouZGlzY3Vzc2lvbkNvbnRhaW5lciwKLmNvbW1lbnRCb3hTdHlsZSwKLnBhZ2Vjb21tZW50LAoucGFnZWNvbW1lbnRoZWFkZXIsCi5jb21fdGV4dCwKLmNvbW1lbnR0eHQsCi5wb3N0LWNvbW1lbnRzLAoucG9zdC1jb21tZW50LWxpc3QsCiNjbXRXcmFwcGVyCgp7CglkaXNwbGF5OiBub25lICFpbXBvcnRhbnQ7Cn0KCgovKiAqKiogV2hpdGVsaXN0IHJ1bGVzICoqKiAqLwoKLyoKICogU29tZSBwYWdlcyB1c2UgYSBjb21tZW50cyBjbGFzcyBvbiB0aGUgdG9wIGxldmVsIGVsZW1lbnQsCiAqIGJsb2NraW5nIHRoZSB3aG9sZSBwYWdlLiBXZWlyZC4KICovCmh0bWwuY29tbWVudHMsIGJvZHkuY29tbWVudHMsCmh0bWwuQ29tbWVudHMsIGJvZHkuQ29tbWVudHMsCmh0bWwjY29tbWVudHMsIGJvZHkjY29tbWVudHMsCmh0bWwjQ29tbWVudHMsIGJvZHkjQ29tbWVudHMsCgovKiBoaWdobGlnaHQuanMgKi8KY29kZSBzcGFuLmNvbW1lbnQsCgovKiBXaWtpcGVkaWEgcmV2aXNpb24gaGlzdG9yeSAqLwojcGFnZWhpc3RvcnkgLmNvbW1lbnQsCnRhYmxlLmRpZmYgLmNvbW1lbnQKCnsKCWRpc3BsYXk6IGluaXRpYWwgIWltcG9ydGFudDsKfQo=">```

This is what breaks premailer. In the `CSSHelper` module, when you get the link tags, you're not taking into account data serialized like above, this gets parsed as `nil` when then blows up in `asset_filename` in `FileSystemLoader`.

Happy to take a look at having a go fixing, but thought I should raise first and let you guys know.

Cheers,
Chris
