### ISSUE TITLE
can't modify frozen String

### ISSUE THREAD

**Issue by meysammeisam** [fphilipe/premailer-rails#247]
After adding `# frozen_string_literal: true` magic comment to my rails app(ruby files), the below exception on hook call is raised:

> 
```ruby
Failure/Error: Premailer::Rails::Hook.perform(mail)
     FrozenError:
       can't modify frozen String
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/css_helper.rb:53:in `force_encoding'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/css_helper.rb:53:in `block in load_css'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/css_helper.rb:46:in `each'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/css_helper.rb:46:in `load_css'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/css_helper.rb:20:in `css_for_url'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/css_helper.rb:13:in `block in css_for_doc'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/css_helper.rb:13:in `map'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/css_helper.rb:13:in `css_for_doc'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/customized_premailer.rb:14:in `initialize'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/hook.rb:97:in `new'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/hook.rb:97:in `premailer'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/hook.rb:86:in `generate_text_part'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/hook.rb:62:in `generate_alternative_part'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/hook.rb:50:in `generate_html_part_replacement'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/hook.rb:24:in `perform'
     # /usr/local/bundle/gems/premailer-rails-1.10.3/lib/premailer/rails/hook.rb:8:in `perform'
...
```

**Comment by fphilipe** [comment]
Not sure why we have this `force_encoding`. I think we don't need this anymore in newer Ruby versions, so I'll just strip it.

**Comment by meysammeisam** [comment]
@fphilipe 
Thanks for the fix. When it will be released?

**Comment by fphilipe** [comment]
I'm waiting for some feedback on #240 as #248 should address that. If I don't hear anything in the next few days, I'll make a new release regardless.

In the meantime, you can point to the repo inside your Gemfile.

**Comment by hwood-sp** [comment]
Agree, would be good to release this, took a while to track down the fix.  For those looking, here's a line for your `Gemfile` in the meantime:

```rb
gem "premailer-rails", github: "fphilipe/premailer-rails", ref: "7202a851ded4687edafca75ee9740dd86c43d96e" # until version >1.10.3 released
```
