### ISSUE TITLE
Ruby 3.3.0 error

### ISSUE THREAD

**Issue by davidwessman** [fphilipe/premailer-rails#289]
Hello

Trying to update my Rails app to run with Ruby 3.3.0 and getting this loading error:

```
<internal:~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- premailer-rails (LoadError)
Did you mean?  premailer/rails
	from <internal:~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.7/lib/bundler/runtime.rb:55:in `each'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.7/lib/bundler/runtime.rb:55:in `block in require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.7/lib/bundler/runtime.rb:44:in `each'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.7/lib/bundler/runtime.rb:44:in `require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.4.7/lib/bundler.rb:195:in `require'
	from ~/programming/rails/blinka/config/application.rb:21:in `<main>'
	from <internal:~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:139:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
	from <internal:~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:~/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from ~/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

Any idea why it cannot load? Something with naming?

**Comment by fphilipe** [comment]
I think Ruby might have translated `require "foo-bar"` to `require "foo/bar"` in the past.

You're supposed to `require "premailer/rails"` for this gem. There is no file `lib/premailer-rails.rb` in this gem, but there is a file `lib/premailer/rails.rb`.

See also the [RubyGems guide on naming](https://guides.rubygems.org/name-your-gem/).

Does that fix your problem?

**Comment by davidwessman** [comment]
There is no mention in the `README` of doing any `require` and it has worked for previous ruby versions.
So this is something that has changed in Ruby 3.3.

Not sure how to fix it in a way that works with Zeitwerk.
Will try to add Ruby 3.3 to the test matrix tomorrow and see if I can find anything.

**Comment by davidwessman** [comment]
It failed because my version of `css_parser` was not updated to a Ruby 3.3-compliant version.
I could find this error when I added a manual `require premailer/rails` in my initializer instead.
